# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Pull request to master

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v5.0.2
      with:
        tag_prefix: "v"
        version_format: "${major}.${minor}.${patch}-prerelease${increment}"
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore --configuration Release -p:Version=${{ steps.version.outputs.version }}
    
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release